# Generated by Django 4.2.4 on 2023-09-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
